-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 19, 2022 at 11:36 AM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `movie`
--

-- --------------------------------------------------------

--
-- Table structure for table `film`
--

CREATE TABLE `film` (
  `imdb_id` varchar(20) CHARACTER SET utf8 NOT NULL,
  `title` varchar(75) CHARACTER SET utf8 DEFAULT NULL,
  `certificate` varchar(5) CHARACTER SET utf8 DEFAULT NULL,
  `startYear` int(11) DEFAULT NULL,
  `endYear` int(11) DEFAULT NULL,
  `type` varchar(40) CHARACTER SET utf8 DEFAULT NULL,
  `orign_country` varchar(40) CHARACTER SET utf8 DEFAULT NULL,
  `plot` varchar(250) CHARACTER SET utf8 DEFAULT NULL,
  `summary` varchar(1750) CHARACTER SET utf8 DEFAULT NULL,
  `genres` varchar(35) CHARACTER SET utf8 DEFAULT NULL,
  `isAdult` int(11) DEFAULT NULL,
  `cast` varchar(420) CHARACTER SET utf8 DEFAULT NULL,
  `image_url` varchar(650) CHARACTER SET utf8 DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `film`
--

INSERT INTO `film` (`imdb_id`, `title`, `certificate`, `startYear`, `endYear`, `type`, `orign_country`, `plot`, `summary`, `genres`, `isAdult`, `cast`, `image_url`) VALUES
('fd001', 'Schumacher', '13+', 2021, NULL, 'Sports', 'Germany', 'Through exclusive interviews and archival footage, this documentary traces an intimate portrait of seven-time Formula 1 champion Michael Schumacher.', 'Schumacher is a 2021 German sports documentary film co-directed by Hanns-Bruno Kammertöns, Vanessa Nöcker, and Michael Wech, about the German Formula One racing driver Michael Schumacher that was distributed internationally on Netflix.', 'Documentary', 0, '[\'Michael Schumacher\']', 'https://m.media-amazon.com/images/M/MV5BOWUzYzBjNjAtN2RlNC00YWE5LThlMDEtMjhlOTQwYTY4NTlmXkEyXkFqcGdeQXVyMTI5Nzk4NDQ4._V1_FMjpg_UX1000_.jpg'),
('fd002', 'Antoine Griezmann: The Making of a Legend', '13+', 2019, NULL, 'Sports', 'France', 'With heart and determination, Antoine Griezmann overcame his small stature to become one of the world\'s top soccer players and a World Cup champion.', 'Antoine Griezmann: The Making of a Legend is a 2019 documentary film directed by Alex Dell, following Antoine Griezmann\'s path from Real Sociedad in Spain, to Atletico Madrid, and all the way to winning the FIFA World Cup with France in 2018. It was released on Netflix on March 21, 2019.', 'Documentary', 0, '[\'Antoine Griezmann\']', 'https://movies-net.com/media/5/antoine-griezmann-the-making-of-a-legend_81049949.jpg'),
('fd003', 'Azzurri Road to Wembley', '13+', 2019, NULL, 'Sports', 'Italy', 'Follows the Italian soccer team\'s road to succes at the 2020 European Championship.', 'Exploring the Italian football team\'s path to victory at the 2020 European Championship, all the way to the riveting final against England.', 'Sports,Movies', 0, '[\'Nicolo Barella\', \'Giorgino Chiellini\']', 'https://occ-0-1167-300.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcoRJgUN4kk4M6RuYXNXK8ROOY_QUU5TjXJQlAIxctmmOu_pH7xFCos3LIJJ6sx7Kwsvm-U4FxDaO-alT_SxZ4fSsgnI.jpg'),
('fd004', 'Anelka Misunderstood', '13+', 2020, NULL, 'Sports', 'France', 'Bad boy of the French football, arrogant, precocious, misunderstood, scorer, unclassifiable, genius, unmanageable. Despite a having a career of almost 20 years at the highest level, Nicolas Anelka is still hard to define.', 'Anelka: Misunderstood is a 2020 British-French documentary sports film directed by Éric Hannezo and features interviews with Nicolas Anelka, Franck Nataf, Omar Sy, Arsène Wenger, Thierry Henry, Didier Drogba, and Emmanuel Petit.', 'Sports,Movies', 0, '[\'Nicholas Anelka\', \'Emmanuel Petit\', \'Thierry Henry\', \'Arsène Wenger\']', 'https://m.media-amazon.com/images/M/MV5BZDE2ZjAxMTEtNzc5MS00ZWFhLTk1M2UtMzQ1ZDhkM2VmMzRkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg'),
('fd005', 'Pele', '14', 2021, NULL, 'Sports', 'Brazil', 'Looks back at the extraordinary 12-year period in which Pelé, the only man to win three World Cup titles, went from young superstar in 1958 to national hero in 1970; a radical yet turbulent era in Brazil’s history.', 'The definitive story of the man who personified soccer, which he called \"the beautiful game\", and how he changed the history of the sport.', 'Documentary', 0, '[\'Pele\']', 'https://m.media-amazon.com/images/M/MV5BODJmYTg4NTEtYTU0Mi00YjQ0LTkyYzEtMTU4MTM2ZWY3NjY4XkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_.jpg'),
('fd006', 'Tony Parker: The Final Shot', '14', 2021, NULL, 'Sports', 'French', 'Examines the background and the career of the french basketball player Tony Parker.', 'Tony Parker: The Final Shot is an 2021 French documentary film, directed by Florent Bodin.', 'Documentary', 0, '[\'Tony Parker\']', 'https://m.media-amazon.com/images/M/MV5BMzlkYzAxM2QtOGZiMy00Zjg1LWFkMTYtZmEyZDAxODk5NDg3XkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_.jpg'),
('fd007', 'The Way Back', '12+', 2020, NULL, 'Sports', 'America', 'Jack Cunningham was a high school basketball phenom who walked away from the game, forfeiting his future. Years later, when he reluctantly accepts a coaching job at his alma mater, he may get one last shot at redemption.', 'Jack, a divorced alcoholic, struggles to maintain social relationships. However, his life changes when he is asked to coach his high school\'s basketball team.', 'Drama,Sport', 0, '[\'Ben Affleck\', \'Janina Gavankar\']', 'https://m.media-amazon.com/images/M/MV5BYjBjMTgyYzktN2U0Mi00YTJhLThkZDQtZmM1ZDlmNWMwZDQ3XkEyXkFqcGdeQXVyMDU5MDEyMA@@._V1_FMjpg_UX1000_.jpg'),
('fd008', 'The Last Dance', '18+', 2020, NULL, 'Sports', 'America', 'Charting the rise of the 1990s Chicago Bulls, led by Michael Jordan, one of the most notable dynasties in sports history.', 'In the fall of 1997, Michael Jordan and the Chicago Bulls allowed a film crew to follow them as they went for their sixth NBA title in eight seasons. That resulted in a stunning portrait of one of the sport\'s most iconic athletes and a celebrated team', 'Drama,Sport', 0, '[\'Michael Jordan\', \'Scottie Pippen\', \'Dennis Rodman\']', 'https://m.media-amazon.com/images/M/MV5BY2U1ZTU4OWItNGU2MC00MTg1LTk4NzUtYTk3ODhjYjI0MzlmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg'),
('fd009', 'Baggio: The Divine Ponytail', '17+', 2021, NULL, 'Sports', 'Italy', 'Biographical film about Italian footballer Roberto Baggio, a man who inspired entire generations to play football. A unique footballer, capable of thrilling fans all over the world.', 'A chronicle of the 22-year career of soccer star Roberto Baggio, including his difficult debut as a player and his deep rifts with some of his coaches.', 'Biography,Drama,Sport', 0, '[\'Andrea Arcangeli\', \'Andrea Pennacchi\', \'Ed Hughes\']', 'https://m.media-amazon.com/images/M/MV5BNWUwYTY0MDItZGVlMS00MDc1LTgxNDYtNmEwNWY0OWYwMDlmXkEyXkFqcGdeQXVyNDI4NTUxMjQ@._V1_FMjpg_UX1000_.jpg'),
('fd010', 'Zero to Hero', '14+', 2021, NULL, 'Sports', 'Japanese', 'Biopic tribute to So Wa Wai, Hong Kong\'s first Paralympic athlete to win gold. Even if you start at a disadvantage, you can still be first across the finish line.', 'Based on the true story of medal-winning Paralympian So Wa-wai, who navigated personal and physical struggles with the help of his mother.', 'Biography,Drama,Sport', 0, '[\'Chung-Hang Leung\',]', 'https://m.media-amazon.com/images/M/MV5BOWIwM2FlOTMtZWZlMi00NTM4LTkxYzktNTJjMGViZTJkYTY3XkEyXkFqcGdeQXVyMjQxNzY5NTc@._V1_.jpg'),
('fd011', 'Unit 42', '17+', 2017, NULL, 'Crime, TvSho', 'French', 'While having to raise his three children on his own, Inspector Sam Leroy joins Brussels\' Cyber Crime Unit. Confronted with new codes, he must collaborate with Billie Vebber, a former hacker who covertly pursues objectives of her own', 'Sam Leroy, an inspector, becomes part of the Brussels Cyber Crime Unit and teams up with Billie Webber, a former hacker, to combat all kinds of cybercrimes.', 'Crime,Drama', 0, '[\'Constance Gay\', \'Patrick Ridremont\']', 'https://m.media-amazon.com/images/M/MV5BY2E3MzI3YzQtN2Y1Yi00ZTQxLWE1ODgtZjI0MDk5MTA0MTJhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg'),
('fd012', 'The Blacklist', '17+', 2013, NULL, 'Crime, TvShows', 'American', 'A new FBI profiler, Elizabeth Keen, has her entire life uprooted when a mysterious criminal, Raymond Reddington, who has eluded capture for decades, turns himself in and insists on speaking only to her.', 'SA wanted fugitive mysteriously surrenders himself to the FBI and offers to help them capture deadly criminals. His sole condition is that he will work only with the new profiler, Elizabeth Keen.', 'Crime,Drama', 0, '[\'James Spader\', \'Megan Boone\']', 'https://m.media-amazon.com/images/M/MV5BNDFkZDI5ZGUtYTdkOC00YTFiLWJjNjMtNTQ3ZjIxMTY2ZjMyXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_FMjpg_UX1000_.jpg'),
('fd013', 'Blackspot', '17+', 2017, NULL, 'Crime, TvShows', 'American', 'A police chief and an eccentric new prosecutor investigate a string of grisly crimes and eerie phenomena in an isolated town at the edge of a forest.', 'A police inspector investigates a string of murders in a town where the murder rate is six times higher than the rest of the country.', 'Crime,Drama', 0, '[\'Camille Aguilar\', \'Brigitte Sy\']', 'https://m.media-amazon.com/images/M/MV5BOTI3Y2VlNjItNzIxMy00OTI4LTkxMWItYzFiY2Q3ODBiOWU2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg'),
('fd014', 'Capitani', '17+', 2019, 2020, 'Crime, TvSho', 'Luxembourg-Fre', 'In a Luxembourg village where everyone is keeping secrets, gruff police inspector Luc Capitani investigates the suspicious death of a 15-year-old girl.', 'Detective Luc Capitani investigates the murder of a teenage girl whose body is found near the village of Manscheid in Luxembourg; having trouble navigating the closed community of the northerners, Capitani teams up with a local policewoman.', 'Crime,Drama', 0, '[\'Luc Schiltz\', \'Sophia Mousel\']', 'https://m.media-amazon.com/images/M/MV5BNzQzMWZmZDctMjMxZS00NzlkLTlkNTYtMmEzOWM0YTFhY2RkXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg'),
('fd015', 'Bridgerton', '17+', 2020, NULL, 'Romance, TvS', 'American-Engla', 'Wealth, lust, and betrayal set against the backdrop of Regency-era England, seen through the eyes of the powerful Bridgerton family.', 'During the Regency era in England, eight close-knit siblings of the powerful Bridgerton family attempt to find love.', 'Drama,Romance', 0, '[\'Jonathan Bailey\', \'Simone Ashley\']', 'https://m.media-amazon.com/images/M/MV5BNjk4MDdhODctMmFhYi00ZTNhLThlN2UtN2NhZGY0OGFlMWEwXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg'),
('fd016', 'Virgin River', '17+', 2019, NULL, 'Romance, TvS', 'American', 'Seeking a fresh start, nurse practitioner Melinda Monroe moves from Los Angeles to a remote Northern California town and is surprised by what and who she finds.', 'Seeking a fresh start, a nurse practitioner moves from Los Angeles to a remote Northern California town and is surprised by what -- and who -- she finds.', 'Drama,Romance', 0, '[\'Martin Henderson\', \'Tim Matheson\']', 'https://m.media-amazon.com/images/M/MV5BMGMzYzFmYzQtODM1OS00ODRhLTk2MjgtMGY5NGE5OTliMjNlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg'),
('fd017', 'Love&Anarchy', '17+', 2020, NULL, 'Romance, TvS', 'Swedish', 'When Sofie, a career-driven consultant and married mother of two, gets an assignment to modernize an old publishing house, she meets young IT tech Max and an unexpected flirting game begins.', 'A married consultant and a young IT technician assign each other challenges that question societal norms in a flirtatious game leading to unintended consequences', 'Drama,Romance', 0, '[\'Jenny Ponce\', Ida Engvoll\']', 'https://m.media-amazon.com/images/M/MV5BZTk3NTU5NzAtNGY0Zi00YTIwLWI0MWUtNTliMmVjOWNiY2VjXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_.jpg'),
('fd018', 'Cable Girls', '14+', 2017, 2020, 'Romance, TvS', 'American', 'Set in the 1920s, this is the story of four women from different backgrounds newly hired as operators for a phone company.', 'It\'s the 1920s and Spain has just gotten its first national telephone company, located in Madrid. For four young women who get jobs there, it\r\n \'s more than just work. ', 'Drama,Romance', 0, '[\'Yon Gonzalez\', \'Ana Fernandez\']', 'https://m.media-amazon.com/images/M/MV5BYmRhMWM4NzQtNTE1OS00NWMxLTgzYzYtMTllZTcyY2NjZDgxXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg'),
('fd019', 'Dating Around', '17+', 2019, NULL, 'Romance, TvS', 'American', 'In a series of flirtations and fails, six real-life singles navigate five blind dates. Their mission: Find one perfect match worthy of a second date.', 'Dating can be tough, so it may be a good idea for singles to go with quantity over quality when hitting the scene to increase their odds of matching with someone.', 'Drama,Romance', 0, '[\'Jarry Lee \', \'Leonard Post\']', 'https://m.media-amazon.com/images/M/MV5BYTIzY2JiMmUtMTI1OC00NDg0LTk0YjQtNTgwZTcxNDNmNTE2XkEyXkFqcGdeQXVyMTY2NzUyMzk@._V1_.jpg'),
('fd020', 'Business Proposal', '14+', 2022, NULL, 'Romance, TvSho', 'Korean', 'In disguise as her friend, Ha-ri shows up to a blind date to scare him away. But plans go awry when he turns out to be her CEO - and makes a proposal.', 'In disguise as her friend, Ha-ri shows up on a blind date to scare away her friend\'s prospective suitor. However, plans go awry when he turns out to be Ha-ri\'s CEO and he makes a proposal.', 'Drama,Romance', 0, '[\'Se-jeong Kim\', \'Seol In-Ah\']', 'https://m.media-amazon.com/images/M/MV5BNjlhMDc5NDMtZGY2Mi00ZTMxLTk0Y2ItN2VjZDQ1ZmRiZGQ2XkEyXkFqcGdeQXVyMTMzODk3NDU0._V1_FMjpg_UX1000_.jpg'),
('fd021', 'Catching Killers', '17+', 2021, NULL, 'Crime, TvSho', 'American', 'The investigators behind infamous serial killer cases reveal the harrowing, chilling details of their extraordinary efforts in this true crime series.', 'Investigators reveal the harrowing details of their efforts to catch serial killers.', 'Crime,Drama', 0, '[\'Charles Coffey\', \'John Ingram\']', 'https://m.media-amazon.com/images/M/MV5BM2MwNjU4ZjQtYWYxNi00MDJlLThlYjItMzY0NTY4MDUyZDA4XkEyXkFqcGdeQXVyMDY2OTkwNQ@@._V1_.jpg'),
('fd022', 'American Murder: The Family Next Door', '17+', 2020, NULL, 'Crime, TvSho', 'American', 'In 2018, 34-year-old Shanann Watts and her two young daughters disappear in Colorado. With the heartbreaking details emerging, the family\'s story made headlines around the world.', 'American Murder: The Family Next Door is an American true crime documentary film directed by Jenny Popplewell. ', 'Crime,Drama', 0, '[\'Nickole Atkinson\', \'Jim Benemann\']', 'https://m.media-amazon.com/images/M/MV5BZjNkOWZlMWYtYmU1Ny00M2ZlLTkzZWUtM2RkMjU0MjM5NmEwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg'),
('fd023', 'Taking Lives', '17+', 2004, NULL, 'Crime, TvSho', 'American', 'An FBI profiler is called in by French Canadian police to catch a serial killer who takes on the identity of each new victim.', 'An FBI profiler is summoned by the agency and entrusted with the responsibility of hunting down a serial killer who assumes the identities of his victims after killing them.', 'Crime,Drama', 0, '[\'Angelina Jolie\', \'Ethan Hawke\']', 'https://m.media-amazon.com/images/M/MV5BMTA3NDMyNzI5NTdeQTJeQWpwZ15BbWU3MDQxNDEyMzM@._V1_.jpg'),
('fd024', 'The Ripper', '17+', 2021, NULL, 'Crime, TvSho', 'England', 'Investigators and witnesses recall how a modern-day Jack the Ripper terrorized the north of England during the late 1970s.', 'Investigators and witnesses recall the Yorkshire Ripper murders, which cast a shadow over the north of England in the late 1970s.', 'Crime,Drama', 0, '[\'Alan Whitehouse\', \'Andrew Laptew\']', 'https://m.media-amazon.com/images/M/MV5BODAxZjliNmMtYjNhZS00OTA3LWFkNzgtOWMyZWMxMmI2M2UxXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_.jpg'),
('fd025', 'Mindhunter', '17+', 2017, 2019, 'Crime, TvSho', 'England', 'Set in the late 1970s, two FBI agents are tasked with interviewing serial killers to solve open cases.', 'Catching a criminal often requires the authorities to get inside the villain\'s mind to figure out how he thinks.That\'s the job of FBI agents Holden Ford and Bill Tench.', 'Crime,Drama', 0, '[\'Jonathan Groff\', \'Anna Torv\']', 'https://m.media-amazon.com/images/M/MV5BNWNmYzQ1ZWUtYTQ3ZS00Y2UwLTlkMDctZThlOTJkMGJiNzBiXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_FMjpg_UX1000_.jpg'),
('fd026', 'Gone Girl', '12', 2014, NULL, 'Crime', 'American', 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.', 'Nick Dunne discovers that the entire media focus has shifted on him when his wife, Amy Dunne, mysteriously disappears on the day of their fifth wedding anniversary.', 'Crime,Drama', 0, 'Ben Affleck , Rosamund Pike', 'https://m.media-amazon.com/images/M/MV5BMTk0MDQ3MzAzOV5BMl5BanBnXkFtZTgwNzU1NzE3MjE@._V1_.jpg'),
('fd027', 'Dr.Romantic', '14+', 2016, 2020, 'Romantic,Movies', 'Korean', '\"Romantic Doctor Kim\" is a \"real doctor\" story set in a small, humble hospital called Dol Dam Hospital. It is a story about people who meet Kim Sa Bu (Han Suk Kyu), a genius doctor, and discover \"real romance.\"', 'A famous surgeon with the nickname of \"Hand of God\" suddenly disappears and resurfaces as \"Teacher Kim\" in a small hospital to guide young doctors.', 'Romantic,Drama,Movies', 0, 'Han Suk-kyu, Woo-min Byeon, Jin Kyung', 'https://m.media-amazon.com/images/M/MV5BN2I0OTAwNWYtODk2NC00MjRkLWJkZDAtMmJmYmZjNWRiYmZhXkEyXkFqcGdeQXVyNDY5MjMyNTg@._V1_.jpg'),
('fd028', 'Holidate', '17+', 2020, NULL, 'Romance,Movies', 'Amerrican', 'Fed up with being single on holidays, two strangers agree to be each other\'s platonic plus-ones all year long, only to catch real feelings along the way.', 'Fed up with being single on holidays, two strangers agree to be each other\'s platonic plus-ones all year long, only to catch real feelings along the way.', 'Romance,Drama,Movies', 0, 'Emma Roberts, Luke Bracey', 'https://m.media-amazon.com/images/M/MV5BYWVmYTFjODItOTY2Ni00NDhhLTk1ZDYtMzBmOGFhZTMyY2Q0XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_FMjpg_UX1000_.jpg'),
('fd029', 'The Notebook', 'PG-13', 2004, NULL, 'Romantic,Movies', 'American', 'A poor yet passionate young man (Ryan Gosling) falls in love with a rich young woman (Rachel McAdams), giving her a sense of freedom, but they are soon separated because of their social differences.', 'Duke reads the story of Allie and Noah, two lovers who were separated by fate, to Ms Hamilton, an old woman who suffers from dementia, on a daily basis out of his notebook.', 'Romantic,Drama,Movies', 0, 'Ryan Gosling, Rachel MacAdams', 'https://m.media-amazon.com/images/M/MV5BMTk3OTM5Njg5M15BMl5BanBnXkFtZTYwMzA0ODI3._V1_FMjpg_UX1000_.jpg'),
('fd030', 'Love Hard', '14+', 2021, NULL, 'Romantic,Movies', 'American', 'An LA girl, unlucky in love, falls for an East Coast guy on a dating app and decides to surprise him for the holidays, only to discover that she\'s been catfished. This lighthearted romantic comedy chronicles her attempt to reel in l', 'After meeting her perfect match on a dating app, an L.A. writer learns she\'s been catfished when she flies 3,000 miles to surprise him for Christmas.', 'Romantic,Drama,Movies', 0, 'Nina Dobrev, Darren Bernet', 'https://m.media-amazon.com/images/M/MV5BODIwNDIxN2YtMWU3ZS00MjU5LWIxMzctNmY1NDg5NDgwYmM0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg'),
('fd031', 'Pets United', '7+', 2019, NULL, 'Kids,Movies', 'American', 'A group of spoilt, selfish pets led by glamour cat Belle are stranded in their luxury hangout \'Pampered Pets,\' when the machines that run Robo City, the hypermodern metropolis that they live in, go wild and take over.', 'Pets United is a 2019 computer-animated comedy film animated film directed and written by Reinhard Klooss and starring Natalie Dormer, Eddie Marsan and Jeff Burrell. It serves as a standalone sequel to the 2010 film Animals United', 'Cartoon', 0, 'Felix Auer, Patrick Roche', 'https://m.media-amazon.com/images/M/MV5BNmU2YTEwODktZDFlNC00YWJmLTk0NjEtMzZjMjM4Y2E3NjdiXkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_.jpg'),
('fd032', 'Peter Rabbit 2: The Runaway', 'PG-13', 2021, NULL, 'Kids,Movies', 'American', 'Thomas and Bea are now married and living with Peter and his rabbit family. Bored of life in the garden, Peter goes to the big city, where he meets shady characters and ends up creating chaos for the whole family.', 'Peter Rabbit runs away from his human family when he learns they are going to portray him in a bad light in their book. Soon, he crosses paths with an older rabbit who ropes him into a heist.', 'Cartoon', 0, '\'[\\\'Rose Bryne\\\']\'', 'https://m.media-amazon.com/images/M/MV5BYjUyN2ZhN2UtNmQ4Zi00N2E5LWI2MmQtYjA3ZDA5MDA0NTFkXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg'),
('fd033', 'Matilda', '7+', 1996, NULL, 'Kids,Movies', 'American', 'A girl gifted with a keen intellect and psychic powers uses both to deal with her crude, distant family and free her kind teacher from their sadistic headmistress.', 'Matilda shares a home with her parents and brother, who do not appreciate her. When her principal tortures her and a kind-hearted teacher, she uses her telekinetic powers to settle scores.', 'Cartoon', 0, '\'[\\\'Danny De Vito\\\']\',\'[\\\'Mara Wilson\\\']\'', 'https://m.media-amazon.com/images/M/MV5BMWE2YTBhYzItZDAxZS00Mjc3LWIxNmYtMzljZjIxMGE1NmY2XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg'),
('fd034', 'Vivo', 'PG-13', 2021, NULL, 'Kids,Movies', 'American', 'Vivo, Sony Pictures Animation\'s first-ever musical adventure featuring all-new original songs from Lin-Manuel Miranda, will take audiences on an epic adventure to gorgeous and vibrant locations never before seen in animation.', 'To fulfil his owner\'s last wish, Vivo, a pet kinkajou, ventures out on a musical adventure where he makes new friends and rediscovers a new meaning to life.', 'Cartoon', 0, 'Zoe Saldana , Ynairaly Simo', 'https://m.media-amazon.com/images/M/MV5BOWQ5MWRkYjMtZTE4ZC00YzM3LTljNzctZTIyY2MxZDY2MzAwXkEyXkFqcGdeQXVyNDI3NjU1NzQ@._V1_.jpg'),
('fd035', 'Yes Day', 'PG-13', 2021, NULL, 'Kids,Movies', 'American', 'A mom and dad who usually say no decide to say yes to their kids\' wildest requests with a few ground rules on a whirlwind day of fun and adventure.', 'Always feeling like they have to say \"no\" to their kids, Allison and Carlos decide to give their three kids a \"Yes Day,\" during which the kids have 24 hours to make the rules.', 'Cartoon', 0, '\'[\'\'Jennifer Garner\'\', \'\'Edgar Ramirez\'\', \'\'Jenna Ortega\'\', ]\'', 'https://m.media-amazon.com/images/M/MV5BNTMwMzA4YzYtMzkwNC00N2ZhLTk5MjQtMjg3ODA3NDY3ZmVmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY1200_CR90,0,630,1200_AL_.jpg'),
('fd036', 'The Loud House', '7+', 2015, NULL, 'Romantic,Movies', 'American', 'Lincoln Loud is an eleven-year-old boy who lives with ten sisters. With the help of his right-hand man Clyde, Lincoln finds new ways to survive in such a large family every day.', 'Lincoln Loud is an 11-year-old who lives with 10 sisters. He along with his best friend Clyde comes up with ways to survive in a large family and finds creative solutions to everyday problems.', 'Romantic,Drama,Movies', 0, 'Grey Griffin , Lara Jill Miller , Jessica DiCicco', 'https://m.media-amazon.com/images/M/MV5BOTg4MTlhMDItNDM1YS00YTM4LWExMmItYTlkMWZhZGRkYWNmXkEyXkFqcGdeQXVyMTM0MTUyMjk1._V1_.jpg'),
('fd037', 'Bee Movie', 'PG-13', 2007, NULL, 'Kids', 'American', 'Barry B. Benson, a bee just graduated from college, is disillusioned at his lone career choice: making honey. On a special trip outside the hive, Barry\'s life is saved by Vanessa, a florist in New York City. As their relationship bl', 'Barry B Benson, a bee who has just completed his graduation, decides to sue humans after he learns about the exploitation of bees at the hands of mankind.', 'Cartoon', 0, 'Jerry Seinfield, Renee Zellweger', 'https://m.media-amazon.com/images/M/MV5BMjE1MDYxOTA4MF5BMl5BanBnXkFtZTcwMDE0MDUzMw@@._V1_.jpg'),
('fd038', 'Dolittle', 'PG-13', 2020, NULL, 'Kids', 'American', 'A physician who can talk to animals embarks on an adventure to find a legendary island with a young apprentice and a crew of strange pets.', 'A physician, who can speak with animals, is summoned by the queen to find a cure for her life-threatening disease. Soon, he embarks on a journey with his furry friends in search of a healing tree.', 'Cartoon', 0, 'Robert Downey Jr. , Antonio Banderas', 'https://m.media-amazon.com/images/M/MV5BMDNkODA5ZGQtODczOS00OTQxLThhMTItMjk0ZmNhMDM0YjNmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_FMjpg_UX1000_.jpg'),
('fd039', 'Larva Island', '7+', 2020, NULL, 'Kids', 'Korea', 'In this movie sequel to the hit series, Chuck returns home and talks to a reporter about life on the island with zany larva pals Red and Yellow', 'He wants to tell the world about his farting, hungry, hilarious island friends. It\'s a tall tale - with tiny co-stars. But will anyone believe him?', 'Cartoon', 0, 'Hong Bum Ki , Eddy Lee , Kang Shi Hyun', 'https://m.media-amazon.com/images/M/MV5BMzhjZDc1MmYtZDcwYy00MjBjLWFkZDAtMGE4YzEwMTdjNjJlXkEyXkFqcGdeQXVyNjA0NDMzNzA@._V1_.jpg'),
('fd040', 'Shrek the Musical', 'TV-G', 2013, NULL, 'Kids', 'American', 'Make room for ogre-sized family fun as the greatest fairy tale never told comes to life in a whole new way in this breathtaking Broadway musical adaptation of the hit movie Shrek!\r\n\r\n', 'Make room for ogre-sized family fun as the greatest fairy tale never told comes to life in a whole new way in this breathtaking Broadway musical adaptation of the hit movie Shrek!', 'Cartoon', 0, 'Brian d\'Arcy, Sutton Foster , Christopher Sieber', 'https://m.media-amazon.com/images/M/MV5BN2U4YzBhNmYtNzAxZS00ZjcyLTg5NDEtMDM4ODVkMTZlZmNkXkEyXkFqcGdeQXVyNzMwOTY2NTI@._V1_.jpg'),
('fd041', 'Rambo: Last Blood', '17+', 2019, NULL, 'Action', 'American', 'Rambo must confront his past and unearth his ruthless combat skills to exact revenge in a final mission.', 'John Rambo\'s peaceful life is interrupted when Gabriela, his friend\'s granddaughter, disappears in Mexico. He decides to free her from the clutches of local cartels, starting a cycle of revenge.', 'Action', 0, 'Sylvester Stallone, Dan Gordon', 'https://m.media-amazon.com/images/M/MV5BNTAxZWM2OTgtOTQzOC00ZTI5LTgyYjktZTRhYWM4YWQxNWI0XkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_.jpg'),
('fd042', 'Mile 22', '17+', 2018, NULL, 'Action', 'American', 'A small team of elite American intelligence officers, part of a top-secret tactical command unit, try to smuggle a mysterious police officer with sensitive information out of Indonesia.', 'James Silva, an American intelligence officer, must ensure that an informant in possession of sensitive information can escape the country safely.', 'Action', 0, 'Mark Wahlberg, Lauran Cohan, Iko Uwais', 'https://m.media-amazon.com/images/M/MV5BNmU3MTJiNGMtMjY2YS00MTg3LWExMWYtZmYzN2Q4MjE3NThlXkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg'),
('fd043', 'The Hard Way', '17+', 2019, NULL, 'Action', 'American', 'After learning his brother died on a mission in Romania, a former soldier teams up with two allies to hunt down a mysterious enemy and exact revenge.', 'After learning of his brother\'s death on a mission in Romania, a former soldier sets off with two allies to hunt down a mysterious enemy and exact revenge.', 'Action', 0, '[\'Michael Jai White\',\'Randy Couture\']', 'https://m.media-amazon.com/images/M/MV5BNTI4NDkzN2MtYjkxMi00YmMzLWJlOWEtNjQ1OTc2MTgyNjQ5XkEyXkFqcGdeQXVyMjA1MTk4Ng@@._V1_.jpg'),
('fd044', 'John Wick (2014)', '17+', 2014, NULL, 'Action', 'American', 'An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.', 'Legendary assassin John Wick (Keanu Reeves) retired from his violent career after marrying the love of his life. Her sudden death leaves John in deep mourning.', 'Action', 0, '[\'Keanu Reeves\']', 'https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_.jpg'),
('fd045', 'S.W.A.T', '17+', 2017, NULL, 'Action', 'American', 'Follows a locally born and bred S.W.A.T. sergeant and his team of highly-trained men and women as they solve crimes in Los Angeles.', 'Sergeant Daniel and his team from the LAPD fight dangerous criminals and strive to protect the public from the threat they impose.', 'Action', 0, '[\'Shemar Moore\',\'Alex Russell\',\'Lina Esco\']', 'https://m.media-amazon.com/images/M/MV5BMTJkMGQxMGItMTlkOC00YWYzLWJhMDEtOTliNjcwNGM1MmFhXkEyXkFqcGdeQXVyNjg4NzAyOTA@._V1_.jpg'),
('fd046', 'Monster Hunter', 'PG-13', 2020, NULL, 'Action', 'American', 'When Cpt. Artemis and her loyal soldiers are transported to a new world, they engage in a desperate battle for survival against enormous enemies with incredible powers. Feature film based on the video game by Capcom.', 'Monster Hunter is a Japanese media franchise centered around a series of fantasy-themed action role-playing video games that started with the game Monster Hunter for PlayStation 2, released in 2004.', 'Action', 0, '[\'Milla Jovovich\',\'Tony Jaa\']', 'https://m.media-amazon.com/images/M/MV5BOGU3NTFmNjYtODc3Ny00MWEzLWI3M2ItZjE3NDgwMTI0MzkzXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg'),
('fd047', 'Collateral', '17+', 2018, NULL, 'Action', 'American', 'London detectives investigating the seemingly random murder of a pizza delivery man uncover a convoluted case of interlocking circumstances amid a cross-section of British society.', '`Collateral\' is a four-part thriller set in London that takes place over four days. When a pizza delivery driver is shot down in South London, Detective Inspector Kip Glaspie, played by `Great Gatsby\' star Carey Mulligan, is left in charge of the investigation', 'Action', 0, '[\'Carey Mulligan\',\'Hayley Squires\']', 'https://m.media-amazon.com/images/M/MV5BNzY2MDg2Njk3MV5BMl5BanBnXkFtZTgwMTE4MTY4NDM@._V1_.jpg'),
('fd048', 'Red (2010)', 'PG-13', 2010, NULL, 'Action', 'American', 'When his peaceful life is threatened by a high-tech assassin, former black-ops agent Frank Moses reassembles his old team in a last-ditch effort to survive and uncover his assailants', 'Frank Moses, a former black-ops agent, learns that his life is under threat from an assassin. In a bid to protect himself, he reunites with his old team to nab the man who has vowed to kill him.', 'Action', 0, '[\'Bruce Willis\',\'Helen Mirren\',\'Morgan Freeman\']', 'https://m.media-amazon.com/images/M/MV5BMzg2Mjg1OTk0NF5BMl5BanBnXkFtZTcwMjQ4MTA3Mw@@._V1_.jpg'),
('fd049', 'No Mercy (2019)', '17+', 2019, NULL, 'Action', 'American', 'A woman seeks to take revenge when her young sister disappears and she finds out that her sister suffered violence and sexual abuse from school bullies.', 'When Eun-hye doesn\'t come home from school, all the alarm bells go off for her older sister, In-ae. She tries to find her own way to save her sister.', 'Action', 0, '[\'Lee si-young\',\'Se-wan Park\']', 'https://m.media-amazon.com/images/M/MV5BYTNmNjNlYjItNzZhNi00OTk0LWJjNWUtY2I5M2RlZDRhZDI1XkEyXkFqcGdeQXVyNzEyMDQ1MDA@._V1_.jpg'),
('fd050', 'John Wick 2', '17+', 2017, NULL, 'Action', 'American', 'After returning to the criminal underworld to repay a debt, John Wick discovers that a large bounty has been put on his life.', 'Renowned assassin John Wick sets out for Rome to duel with some of the deadliest killers to fulfil a vow he made. However, he soon learns that there is a huge bounty on his head.', 'Action', 0, '[\'Keanu Reeves\']', 'https://m.media-amazon.com/images/M/MV5BMjE2NDkxNTY2M15BMl5BanBnXkFtZTgwMDc2NzE0MTI@._V1_.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `film`
--
ALTER TABLE `film`
  ADD PRIMARY KEY (`imdb_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
